import { build as viteBuild, mergeConfig, type UserConfig } from "vite";
import path from "path";
import { copyFile, readFile, rm, writeFile } from "fs/promises";
import baseConfig from "../vite.config";

const rootDir = path.resolve(import.meta.dirname, "..");
const clientRoot = path.resolve(rootDir, "client");
const themeRoot = path.resolve(rootDir, "shopify-theme");
const assetsDir = path.resolve(themeRoot, "assets");
const snippetAssetsPath = path.resolve(themeRoot, "snippets", "uonimiq-assets.liquid");
const snippetScriptsPath = path.resolve(themeRoot, "snippets", "uonimiq-scripts.liquid");

async function buildShopifyTheme() {
  process.env.NODE_ENV = "production";

  const shopifyConfig: UserConfig = {
    root: clientRoot,
    build: {
      outDir: assetsDir,
      emptyOutDir: true,
      manifest: true,
      assetsDir: "",
      rollupOptions: {
        input: path.resolve(clientRoot, "index.html"),
      },
    },
  };

  await viteBuild(mergeConfig(baseConfig as UserConfig, shopifyConfig));

  const manifestPath = path.resolve(assetsDir, "manifest.json");
  const manifestRaw = await readFile(manifestPath, "utf-8");
  const manifest = JSON.parse(manifestRaw) as Record<
    string,
    { file: string; css?: string[]; isEntry?: boolean }
  >;

  const entry = Object.values(manifest).find((item) => item.isEntry);
  if (!entry) {
    throw new Error("Vite manifest entry not found.");
  }

  const cssTags = (entry.css || [])
    .map((file) => `{{ '${file}' | asset_url | stylesheet_tag }}`)
    .join("\n");
  const jsTag = `<script type=\"module\" src=\"{{ '${entry.file}' | asset_url }}\"></script>`;

  await writeFile(
    snippetAssetsPath,
    `{% comment %}Auto-generated by script/build-shopify.ts{% endcomment %}\n${cssTags}\n`,
    "utf-8"
  );
  await writeFile(
    snippetScriptsPath,
    `{% comment %}Auto-generated by script/build-shopify.ts{% endcomment %}\n${jsTag}\n`,
    "utf-8"
  );

  const publicVideo = path.resolve(clientRoot, "public", "videos", "hero.mp4");
  const publicFavicon = path.resolve(clientRoot, "public", "favicon.png");
  await copyFile(publicVideo, path.resolve(assetsDir, "hero.mp4"));
  await copyFile(publicFavicon, path.resolve(assetsDir, "favicon.png"));

  await rm(manifestPath, { force: true });
}

buildShopifyTheme().catch((err) => {
  console.error(err);
  process.exit(1);
});
